baseURL = "https://weilumeng6.github.io/"
languageCode = "en-us"
title = "Weilu Meng"
theme = "hugo-ht"
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true

[[menu.en]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.en]]
    name = "Research"
    url = "/research/"
    weight = 2

[[menu.en]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3

[[menu.en]]
    name = "Conferences"
    url = "/conference/"
    weight = 4

[params]
    description = "Personal academic website of Weilu Meng"
    homeText = "PhD Student in Economics, The University of Queensland"
    blogDirName = "blog"
    singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    favicon = "image/Vicky.jpg"
    GithubEdit = "https://github.com/WeiluMeng/WeiluMeng.github.io/edit/master/content/"
    copyright = "&copy;"
    copyrightYear = "2022-2026"
    GithubRepo = "https://github.com/WeiluMeng/WeiluMeng.github.io"
    ContentSource = "https://raw.githubusercontent.com/WeiluMeng/WeiluMeng.github.io/master/content/"

[params.logo]
    url = "image/Vicky.jpg"
    width = 70.0
    height = 70.0
    alt = "Weilu Meng"

[params.lang]

    [params.lang.author]
      en = "Weilu Meng"

    [params.lang.madeWith]
      en = "Made with"

    [params.lang.edit]
      en = "Suggest an edit of this page"

    [params.lang.lastupdate]
      en = "Last modified on"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"

    [params.lang.sourceCode]
      en = "Content in"

    [params.lang.subscribe]
      en = "Subscribe"

    [params.lang.license]
      en = "License"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = false
      strikethrough = true
      table = true
      taskList = true
      typographer = true

    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true

    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[imaging]
quality = 100

[caches]
  [caches.images]
    dir = ':cacheDir/images'